### ISSUE TITLE
Crash when hovering any tool

### ISSUE THREAD

**Issue by hokomili** [TeamAOF/All-of-Fabric-7#16]
version: 0.3.0
[crash-2023-09-04_15.31.56-client.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12511316/crash-2023-09-04_15.31.56-client.txt)

**Comment by hokomili** [comment]
It seems that sodium is the issue and should have been removed, but curseforge still installed it because Reese's Sodium Options depends on Sodium.
Anyway turned off both and it worked.

**Comment by Teboran** [comment]
Mods that I had to remove:

Iris
Indium
Reese's 
Sodium mc1.20-0.4.10

**Comment by hokomili** [comment]
Updating those 4 mods to the latest version seemed to work as well.
But you'll have to download them manually from modrinth because sodium decided to not update on curseforge.
I think I'll keep this issue open until there's a better solution.

**Comment by Kazuhiko-Gushiken** [comment]
@hokomili @Teboran This is known and is caused by a wrong default config.

Look for the config file: `legendarytooltips-common.toml`

Inside of it set:
`render_item_model = "EQUIPMENT" to`
to this:
`render_item_model = "NONE"`

The item rendering in the tooltip is bugged and causing your crash. Disabling it will allow you to re-install Sodium and other mods in the same family for the gained performance and the dependency that is Indium

**Comment by hokomili** [comment]
Close as the lastest update resolved it
