### ISSUE TITLE
crash on start up 

### ISSUE THREAD

**Issue by Minecrafterthebuilder** [TeamAOF/All-of-Fabric-7#162]
fabric is outdated and requires a version 15.0 or higher

**Comment by SubordinalBlue** [comment]
What mods did you add?

The pack starts with with the modset it has, including Fabric loader 0.14.25

**Comment by Minecrafterthebuilder** [comment]
i added the new wurst update because i use it in my singleplayer worlds for easier playthroughs and it just crashes on startup

**Comment by SubordinalBlue** [comment]
Not every mod will work together at the same time... that's part of putting a pack together, finding out which ones (and which versions) work together.

Since AoF7 is not (yet?) on fabric loader 0.15 (for reasons), maybe try an earlier version of this mod you want?

**Comment by Kazuhiko-Gushiken** [comment]
The pack is currently set to FAPI 0.14.25 because any newer version causes some of the mods we currently use to not function at all. The current version is the only version that has all the (default) mods working properly. Once we're able to update the FAPI version safely, then it will be done, but for now it's not possible without having to remove mods.

**Comment by Minecrafterthebuilder** [comment]
Ok, thank you.
