### ISSUE TITLE
Some quick mod recommendations

### ISSUE THREAD

**Issue by LambdAurora** [TeamAOF/All-of-Fabric-7#2]
- Lovely Snails (obviously I'm biased, *but* it was part of AoF 4 and AoF 5 so it could be nice to see it come back)
- Ears (always a nice to have for player skin customization, especially for multiplayer)

**Comment by warior456** [comment]
Sculk Depths (biased but better than deeper and darker(in world gen, visuals, lore and not forcing you to kill the warden))

**Comment by mattague** [comment]
Would love to see immersive portals be added.

**Comment by Kazuhiko-Gushiken** [comment]
@mattague Immersive portals is a very neat mod, but it causes extreme lag on lower end computer, laptops, and older computers. If you plan to play singeplayer or on a private server, having everyone add it after the fact should be completely possible, but as a base modpack, it could be a problem.

Just my take though.

**Comment by Redstonewarrior0** [comment]
Storage drawers would be an excellent addition. Having something like the compacting drawer would be amazing. Unfortunately, Storage Drawers is a Forge mod.

It's a good thing I bothered checking for a fabric variant.  Look at Extended Drawers and see if it would work well in All of Fabric 7.

**Comment by WraithStar** [comment]
> Would love to see immersive portals be added.

Not possible. That mod has lots of compatibility issues with many mods (e.g. Spectrum and many others), and works only with Iris 1.4.0, which is pretty old.

**Comment by WraithStar** [comment]
so here are some mods i've added to my custom edit of the old AOF6 which worked quite well


## Performance and utilities
- [AMECS](https://modrinth.com/mod/amecs) (had to remove Controlling because of an incompatibility, but this one is far superior - it's quite important)
- [Borderless Mining](https://modrinth.com/mod/borderless-mining)
- [Memory Leak Fix](https://modrinth.com/mod/memoryleakfix)
- [No Telemetry](https://modrinth.com/mod/no-telemetry)
- [Starlight (Fabric)](https://modrinth.com/mod/starlight)


## UI
- [BetterF3](https://modrinth.com/mod/betterf3)  
- [Dynamic Crosshair](https://modrinth.com/mod/dynamiccrosshair)
  - [Dynamic Crosshair Compat](https://modrinth.com/mod/dynamiccrosshaircompat)
- [Emojiful](https://modrinth.com/mod/emojiful)
- [ExtraSounds](https://modrinth.com/mod/extrasounds)
- [Item Borders](https://modrinth.com/mod/item-borders)
- [Item Highlighter](https://modrinth.com/mod/item-highlighter)
- [Overflowing Bars](https://modrinth.com/mod/overflowing-bars)
- [Pickup Notifier](https://modrinth.com/mod/pick-up-notifier)
- [Styled Player List](https://modrinth.com/mod/styledplayerlist)

## Gameplay 
- [Bits and Chisels](https://modrinth.com/mod/bits-and-chisels) - a very good replacement for Chisels and Bits
- [Bountiful](https://modrinth.com/mod/bountiful)
- [Combat Roll](https://modrinth.com/mod/combat-roll)
- [Easy Magic](https://modrinth.com/mod/easy-magic) 
- [Enchanting Infuser](https://modrinth.com/mod/enchanting-infuser)
- [EnhancedVisuals](https://modrinth.com/mod/enhancedvisuals)
- [Fabric Seasons](https://modrinth.com/mod/fabric-seasons) and addons
- [Gearifiers](https://modrinth.com/mod/gearifiers)
- [HT's TreeChop](https://modrinth.com/mod/treechop)
- [Jewelry (RPG Series)](https://modrinth.com/mod/jewelry)
- [Lamb's Dynamic Lights](https://modrinth.com/mod/lambdynamiclights) (hi @LambdAurora :P)
- [LevelZ](https://modrinth.com/mod/levelz) and addons (it didn't really work in 1.19, I had to use [PlayerEx](https://modrinth.com/mod/playerex) plus addons for some reason but I see it works in 1.20)
- [Numismatic Overhaul](https://modrinth.com/mod/numismatic-overhaul) 
- [Paladins & Priests (RPG Series)](https://modrinth.com/mod/paladins-and-priests)

## Fun and other
- [Better Animations Collection](https://modrinth.com/mod/better-animations-collection)
- [Emotecraft](https://modrinth.com/mod/emotecraft)
- [Immersive Paintings](https://modrinth.com/mod/immersive-paintings)
- [Spawn Animations](https://modrinth.com/datapack/spawn-animations)

## World generation
- [Terralith](https://modrinth.com/mod/terralith)
- [BetterEnd](https://modrinth.com/mod/betterend)
- [BetterNether](https://modrinth.com/mod/betternether)

**Comment by hanakin** [comment]
look at adding extended drawers which is a fabric mod equivalent to storage drawers https://www.curseforge.com/minecraft/mc-mods/extended-drawers

**Comment by SubordinalBlue** [comment]
All good suggestions with merit.

The [AOF Studios discord server](https://discord.gg/6rkdm48) has a thread for discussion mod suggestions: https://discord.com/channels/570630340075454474/1137504934695280663.

I'd recommend that for free-form discussion of many mod suggestions, like this issue has turned into.

IMHO, repo issues would be a better fit for single suggestions, or at least one person's single post of suggestions.
