### ISSUE TITLE
Disable MouseTweaks Wheel Tweak by default

### ISSUE THREAD

**Issue by clbx** [TeamAOF/All-of-Fabric-7#50]
MouseTweaks WheelTweak adds the functionality to move items between inventories using the scroll wheel, but this makes using the ME terminals borderline unusable. 

This feature seems like something only some people will want while making a large part of the pack annoying to use. 

This is not expected behavior for people unfamiliar with MouseTweaks and many people will not know how to disable it.

**Comment by SubordinalBlue** [comment]
II hear you. Myself, I otherwise like mousetweaks so I just adapted to moving my mouse to an area clear of the ae2 terminal’s inventory before scrolling the terminal. That may or may not work for you, though I could assume you’ve already turned mousetweaks off for yourself.

Workarounds aside, this seems to be rarely requested so one could guess the majority of players are better served with it enabled.

**Comment by iteathen** [comment]
I second the motion to set WheelTweak=0. It can cause a huge head ache in me crafting terminal as you spend the next two hours trying to track down where all the patterns where suppose to go after WheelTweek sucked them all out of the pattern providers.

**Comment by Kazuhiko-Gushiken** [comment]
I actually do agree with this. I'd be willing to set wheel tweak to default off with AK's permission.

**Comment by unilock** [comment]
I made a mod that disables Mouse Tweaks' "WheelTweak" in AE2 terminals specifically: https://github.com/unilock/AE2MouseTweaksFix

It'll be on Modrinth as well soon.

**Comment by SubordinalBlue** [comment]
Forgot to comment: unilock's mod was added to the pack, resolving the issue.
