### ISSUE TITLE
chisel has no recipe

### ISSUE THREAD

**Issue by Atyneton** [TeamAOF/All-of-Fabric-7#74]
AK you told me to write a report, chisel from rechiseled has no recipe, and none of the blocks from the mod have any recipes either.

**Comment by natereprogle** [comment]
Same here, chisel has no recipe, as it clashes with the Iron Sai from Simply Swords. However, the blocks from the mod don't have recipes because they're supposed to be made via the chisel, so I _think_ that's intended, but I haven't used rechiseled before so idk

**Comment by Kazuhiko-Gushiken** [comment]
There should be a mod called "Polymorph" to deal with the conflicting recipes. If you don't see the button above the output slot, stop using the Crafting Station as those don't support polymorph.

**Comment by natereprogle** [comment]
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/4064388/c2f30092-b0b8-42ce-a097-174c04972f67)
Polymorph button does not exist in the standard crafting table in the latest version of AOF 7. In fact, REI doesn't even show a recipe for the chisel _at all_.

**Comment by Kazuhiko-Gushiken** [comment]
@natereprogle @Atyneton I found the reason there was no recipe. The recipe in the files called for `ad_astra:iron_rod` which had disappeared after the recipe unification. Because iron rod was a little too forceful into MI or Create for something unneeded for progression, I've tweaked the recipe to make it a little easier and it should let you craft upon next update.
